export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export ZDOTDIR="$XDG_CONFIG_HOME"/zsh

export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export LESSHISTFILE="-"

export CARGO_HOME="$XDG_DATA_HOME"/cargo
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export NPM_CONFIG_GLOBALCONFIG="$XDG_DATA_HOME"/npm

if [ -d $HOME/.local/bin ]; then
  if [[ ! $PATH =~ $HOME/.local/bin ]]; then
    export PATH=$HOME/.local/bin:$PATH
  fi
fi
