return {
  "nvim-treesitter/nvim-treesitter",
  event = { "BufReadPre", "BufNewFile" },
  build = ":TSUpdate",
  dependencies = {
    { "nvim-treesitter/nvim-treesitter-context", opts = {} },
  },
  opts = {
    ensure_installed = {
      "astro",
      "bash",
      "c",
      "cpp",
      "css",
      "diff",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitcommit",
      "gitignore",
      "gnuplot",
      "gpg",
      "html",
      "java",
      "javascript",
      "jsdoc",
      "json",
      "latex",
      "lua",
      "make",
      "markdown_inline",
      "matlab",
      "meson",
      "python",
      "regex",
      "rust",
      "svelte",
      "toml",
      "tsx",
      "typescript",
      "verilog",
      "vim",
      "vimdoc",
      "yaml",
      "zathurarc",
    },
    highlight = {
      enable = true,
      additional_vim_regex_highlighting = false,
    },
    indent = { enable = true },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = "<Enter>",
        node_incremental = "<Enter>",
        node_decremental = "<BS>",
      },
    },
    auto_install = false,
  },
  config = function(_, opts)
    require("nvim-treesitter.install").prefer_git = true
    require("nvim-treesitter.configs").setup(opts)
  end,
}
